server:
  port: 8001
spring:
  profiles:
    active: dev
  application:
    name: zfcard
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-actual-param-name: true
  global-config:
    db-config:
      logic-delete-field: defFlag
      logic-delete-value: 0
      logic-not-delete-value: 1
      id-type: auto
  mapper-locations: classpath:mapper/**/*Mapper.xml

# swagger 扫描爆红问题
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
